-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.customers
(
    customers_id integer,
    customers_login "char",
    customers_email "char",
    password_1 "char",
    password_2 "char",
    first_name "char",
    middle_name "char",
    last_name "char",
    customers_phone integer,
    customers_country "char",
    customers_city "char",
    customers_adress "char",
    PRIMARY KEY (customers_login)
);

CREATE TABLE public.material_type
(
    material_id integer,
    material_title "char",
    PRIMARY KEY (material_title)
);

CREATE TABLE public.colors
(
    colors_id integer,
    colors_title "char",
    PRIMARY KEY (colors_title)
);

CREATE TABLE public.category_item
(
    category_item_id integer,
    category_item_title "char",
    PRIMARY KEY (category_item_title)
);

CREATE TABLE public.subcategory
(
    subcategory_id integer,
    subcategory_type "char",
    subcategory_product "char",
    PRIMARY KEY (subcategory_product)
);

CREATE TABLE public.payment_methods
(
    payment_methods_id integer,
    payment_methods__title "char",
    PRIMARY KEY (payment_methods__title)
);

CREATE TABLE public.product
(
    product_id integer,
    product_category "char",
    product_description "char",
    product_select_material "char",
    product_select_color "char",
    product_size integer,
    extra_parameter_1 boolean,
    extra_parameter_2 boolean,
    extra_parameter_3 boolean,
    product_title "char",
    PRIMARY KEY (product_title)
);

CREATE TABLE public."order"
(
    order_id integer,
    order_customer "char",
    order_payment_type "char",
    order_wallet_pay "char",
    end_adress_delivery "char",
    full_name_reciplent "char",
    order_date time with time zone,
    order_buy_item "char"
);

CREATE TABLE public.order_product
(
    order_order_buy_item "char",
    product_product_title "char"
);

CREATE TABLE public.customers_basket
(
    customers_basket_id integer,
    customers_basket_login "char",
    customers_basket_items "char",
    PRIMARY KEY (customers_basket_items)
);

CREATE TABLE public.customers_basket_product
(
    customers_basket_customers_basket_items "char",
    product_product_title "char"
);

ALTER TABLE public.subcategory
    ADD FOREIGN KEY (subcategory_type)
    REFERENCES public.category_item (category_item_title)
    NOT VALID;


ALTER TABLE public.product
    ADD FOREIGN KEY (product_category)
    REFERENCES public.subcategory (subcategory_product)
    NOT VALID;


ALTER TABLE public.product
    ADD FOREIGN KEY (product_select_material)
    REFERENCES public.material_type (material_title)
    NOT VALID;


ALTER TABLE public.product
    ADD FOREIGN KEY (product_select_color)
    REFERENCES public.colors (colors_title)
    NOT VALID;


ALTER TABLE public."order"
    ADD FOREIGN KEY (order_customer)
    REFERENCES public.customers (customers_login)
    NOT VALID;


ALTER TABLE public."order"
    ADD FOREIGN KEY (order_payment_type)
    REFERENCES public.payment_methods (payment_methods__title)
    NOT VALID;


ALTER TABLE public.order_product
    ADD FOREIGN KEY (product_product_title)
    REFERENCES public.product (product_title)
    NOT VALID;


ALTER TABLE public.customers_basket
    ADD FOREIGN KEY (customers_basket_login)
    REFERENCES public.customers (customers_login)
    NOT VALID;


ALTER TABLE public.customers_basket_product
    ADD FOREIGN KEY (customers_basket_customers_basket_items)
    REFERENCES public.customers_basket (customers_basket_items)
    NOT VALID;


ALTER TABLE public.customers_basket_product
    ADD FOREIGN KEY (product_product_title)
    REFERENCES public.product (product_title)
    NOT VALID;

END;