-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

CREATE DATABASE hedgehogshop; 
\c hedgehogshop 

CREATE TABLE public.pays_mthods
(
    id integer,
    name "char",
    PRIMARY KEY (name)
);

CREATE TABLE public.customer_payment
(
    id integer,
    customer_id integer,
    type_pay "char",
    number_records_references integer,
    code integer
);

CREATE TABLE public.customers
(
    id integer,
    nicnname "char",
    password "char",
    email "char",
    first_name "char",
    middle_name "char",
    last_name "char",
    phone "char",
    adress "char",
    city "char",
    country "char",
    PRIMARY KEY (id)
);

CREATE TABLE public.category
(
    id integer,
    category "char"
);

CREATE TABLE public.category_product
(
    id integer,
    type "char",
    category "char",
    PRIMARY KEY (type)
);

CREATE TABLE public.product
(
    id integer,
    category "char",
    title "char",
    description "char",
    material_type "char",
    color "char",
    size integer,
    extra_parameter_1 boolean,
    extra_parameter_2 boolean,
    extra_parameter_3 boolean,
    PRIMARY KEY (category, material_type, color)
);

CREATE TABLE public.material
(
    id integer,
    title "char"
);

CREATE TABLE public.color
(
    id integer,
    title "char"
);

CREATE TABLE public.orders
(
    id integer,
    customer_order "char",
    payment_type "char",
    wallet_number "char",
    items "char",
    adress "char",
    name "char",
    PRIMARY KEY (id, items)
);

CREATE TABLE public.basket
(
    id integer,
    customer_basket "char",
    items "char",
    PRIMARY KEY (customer_basket, items)
);

CREATE TABLE public.basket_product
(
    basket_items "char",
    product_title "char"
);

CREATE TABLE public.orders_product
(
    orders_items "char",
    product_title "char"
);

ALTER TABLE public.customer_payment
    ADD FOREIGN KEY (type_pay)
    REFERENCES public.pays_mthods (name)
    NOT VALID;


ALTER TABLE public.customer_payment
    ADD FOREIGN KEY (customer_id)
    REFERENCES public.customers (id)
    NOT VALID;


ALTER TABLE public.category_product
    ADD FOREIGN KEY (type)
    REFERENCES public.category (category)
    NOT VALID;


ALTER TABLE public.product
    ADD FOREIGN KEY (material_type)
    REFERENCES public.material (title)
    NOT VALID;


ALTER TABLE public.product
    ADD FOREIGN KEY (color)
    REFERENCES public.color (title)
    NOT VALID;


ALTER TABLE public.orders
    ADD FOREIGN KEY (customer_order)
    REFERENCES public.customers (id)
    NOT VALID;


ALTER TABLE public.orders
    ADD FOREIGN KEY (payment_type)
    REFERENCES public.pays_mthods (name)
    NOT VALID;


ALTER TABLE public.basket
    ADD FOREIGN KEY (customer_basket)
    REFERENCES public.customers (id)
    NOT VALID;


ALTER TABLE public.basket_product
    ADD FOREIGN KEY (basket_items)
    REFERENCES public.basket (items)
    NOT VALID;


ALTER TABLE public.basket_product
    ADD FOREIGN KEY (product_title)
    REFERENCES public.product (title)
    NOT VALID;


ALTER TABLE public.orders_product
    ADD FOREIGN KEY (orders_items)
    REFERENCES public.orders (items)
    NOT VALID;


ALTER TABLE public.orders_product
    ADD FOREIGN KEY (product_title)
    REFERENCES public.product (title)
    NOT VALID;

END;